#!/usr/bin/env python3
"""Fail-closed, ATOMIC paper build: paper.src.md + facts -> md -> build.md -> tex/pdf.

Pipeline (every gate aborts BEFORE anything reaches the canonical paths):
  1. facts.py computes every artifact-backed number, asserting against artifacts.
  2. paper.src.md placeholders are substituted. Gates:
       - strict placeholder grammar: every word-like {{ ... }} must be an exact
         {{known_fact}} (mistyped, spaced, or unknown names abort; quoted dbt
         Jinja like {{ ref(…) }} is non-word and passes as prose)  -> abort
       - any adversarially-gated phrase (whitespace-normalized; single shared
         list at repro/gated_phrases.json)                       -> abort
       - any UNUSED fact whose value string nevertheless appears in the render
         (a hand-written copy of a derived number — the staleness hazard)
                                                                 -> abort
  3. All four outputs are produced in a STAGING directory (paper/.staging/).
  4. repro/verify_claims.py runs against the staging outputs (PAPER_DIR env);
     it must exit 0. Only then are the outputs atomically moved into place —
     a rejected build leaves the canonical files untouched.

paper-v3.md / -build.md / .tex / .pdf are OUTPUTS. Hand-edits belong in
paper.src.md only; verify_claims independently re-renders the source and
byte-compares, so a hand-edit to a generated file FAILS the checker.
"""
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from facts import facts  # noqa: E402

BANNER = ("<!-- GENERATED by paper/build.py from paper.src.md + paper/facts.py — "
          "DO NOT HAND-EDIT. Edit paper.src.md instead. -->\n")
OUTPUTS = ("paper-v3.md", "paper-v3-build.md", "paper-v3.tex", "paper-v3.pdf")


def gated_phrases():
    return json.load(open(os.path.join(ROOT, "repro", "gated_phrases.json")))["phrases"]


def render():
    """paper.src.md + facts -> final markdown body (no banner). All gates run here."""
    src = open(os.path.join(HERE, "paper.src.md"), encoding="utf-8").read()
    F = facts()
    # STRICT placeholder grammar (round-7 fix, refined): a placeholder is exactly
    # {{name}} with name = [a-z0-9_]+ and a known fact. Any {{ ... }} whose inner
    # text is WORD-LIKE ([A-Za-z0-9_ ]+) but not an exact known placeholder is a
    # malformed/unknown placeholder -> abort ({{BogusFact}}, {{ spaced_name }}).
    # Non-word inner text (quoted dbt Jinja like {{ ref(…) }} or {{ config() }})
    # is prose and passes through untouched.
    for m in re.finditer(r"\{\{\s*([A-Za-z0-9_]+)\s*\}\}", src):
        exact = "{{" + m.group(1) + "}}"
        if m.group(0) != exact or m.group(1) not in F:
            sys.exit(f"BUILD FAILED — malformed or unknown placeholder: {m.group(0)!r}")
    out = src
    used = set()
    for k, v in F.items():
        if "{{" + k + "}}" in out:
            used.add(k)
        out = out.replace("{{" + k + "}}", v)
    norm = re.sub(r"\s+", " ", out)
    hits = [p for p in gated_phrases() if re.sub(r"\s+", " ", p) in norm]
    if hits:
        sys.exit(f"BUILD FAILED — gated phrases present: {hits}")
    # hand-written copies of derived numbers: an unused fact's value in the text
    # is exactly the staleness hazard this pipeline exists to kill. Short or
    # deliberately-ambiguous values (< 3 chars) are exempt — they cannot be
    # attributed to a fact by string match.
    handwritten = sorted(k for k, v in F.items()
                         if k not in used and len(v) >= 3 and v in norm)
    if handwritten:
        sys.exit("BUILD FAILED — derived facts appear hand-written in the source "
                 f"(inject the placeholder instead): {handwritten}")
    return out


def derive_build_md(md):
    lines = [ln for ln in md.splitlines() if not ln.startswith("<!-- GENERATED")]
    title = lines[0].lstrip("# ").strip()
    out = []
    for ln in lines[1:]:
        m = re.match(r"^(#{2,6})(\s+.*)$", ln)
        out.append(m.group(1)[1:] + m.group(2) if m else ln)
    yaml = ("---\n"
            f'title: "{title}"\n'
            "date: 2026-07-10\n"
            "geometry: margin=1in\n"
            "fontsize: 11pt\n"
            "colorlinks: true\n"
            "---\n\n")
    return yaml + "\n".join(out).strip() + "\n"


def main():
    check_only = "--check" in sys.argv
    md = render()
    if check_only:
        print("render OK (check mode, nothing written)")
        return
    staging = os.path.join(HERE, ".staging")
    # Concurrent-build guard: os.makedirs without exist_ok is an atomic
    # test-and-claim — a second build racing this one aborts instead of
    # deleting the first one's staging out from under it (observed race).
    if os.path.isdir(staging):
        sys.exit("BUILD FAILED — another build appears to be in progress "
                 "(paper/.staging exists); remove it only if that build is dead")
    os.makedirs(staging)
    open(os.path.join(staging, "paper-v3.md"), "w", encoding="utf-8").write(BANNER + md)
    open(os.path.join(staging, "paper-v3-build.md"), "w", encoding="utf-8").write(derive_build_md(md))
    for cmd in (
        ["pandoc", "paper-v3-build.md", "-s", "-o", "paper-v3.tex"],
        ["pandoc", "paper-v3-build.md", "-s", "--pdf-engine=xelatex",
         "-V", "mainfont=DejaVu Serif", "-V", "monofont=DejaVu Sans Mono",
         "-V", "sansfont=DejaVu Sans", "-V", "CJKmainfont=Noto Serif CJK SC",
         "-o", "paper-v3.pdf"],
    ):
        r = subprocess.run(cmd, cwd=staging, capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"BUILD FAILED — {cmd[0]} {cmd[-1]}: {r.stderr[:400]}")
        if "Missing character" in r.stderr:
            sys.exit(f"BUILD FAILED — missing glyphs in {cmd[-1]}")
    env = dict(os.environ)
    env["PAPER_DIR"] = staging
    r = subprocess.run([sys.executable, os.path.join(ROOT, "repro", "verify_claims.py")],
                       capture_output=True, text=True, env=env)
    if r.returncode != 0:
        sys.exit("BUILD FAILED — independent checker rejected the STAGED build "
                 "(canonical files untouched):\n" + r.stdout[-1200:])
    for name in OUTPUTS:
        os.replace(os.path.join(staging, name), os.path.join(HERE, name))
    shutil.rmtree(staging, ignore_errors=True)
    print("BUILD OK — staged outputs verified by the independent checker, "
          "then atomically installed")


if __name__ == "__main__":
    main()
