#!/usr/bin/env python3
"""Fail-closed paper build: paper.src.md + facts -> paper-v3.md -> build.md -> tex/pdf.

Pipeline (any failure aborts the build, nothing is written):
  1. facts.py computes every artifact-backed number (asserting against artifacts).
  2. paper.src.md placeholders {{name}} are substituted; ANY unresolved placeholder
     or unused-but-referenced fact aborts.
  3. The rendered text is swept for adversarially-gated phrases (whitespace-
     normalized) — a hit aborts.
  4. paper-v3.md is written WITH a generated-file banner; paper-v3-build.md is
     derived (title -> YAML, headings shifted); pandoc produces tex + pdf.
  5. repro/verify_claims.py (the INDEPENDENT checker) must exit 0.

paper-v3.md / -build.md / .tex / .pdf are OUTPUTS. Hand-edits belong in
paper.src.md only.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from facts import facts  # noqa: E402

BANNER = ("<!-- GENERATED by paper/build.py from paper.src.md + paper/facts.py — "
          "DO NOT HAND-EDIT. Edit paper.src.md instead. -->\n")

FORBIDDEN_PHRASES = [
    "fell from 5 to 0", "EUSES-full)", "stated open", "shares no files",
    "identical files, so the growth", "164 of the 500", "164 EUSES files",
    "categories (cs101 9", "452,384 unique real formulas ×", "from v1's 5",
    "7,419- and", "exactly the certifiable class of",
    "went 0/2 (v1) → 0/0 (v2) (§5.10) — because",
]


def render():
    src = open(os.path.join(HERE, "paper.src.md"), encoding="utf-8").read()
    F = facts()
    out = src
    for k, v in F.items():
        out = out.replace("{{" + k + "}}", v)
    unresolved = sorted(set(re.findall(r"\{\{[a-z0-9_]+\}\}", out)))
    if unresolved:
        sys.exit(f"BUILD FAILED — unresolved placeholders: {unresolved}")
    norm = re.sub(r"\s+", " ", out)
    hits = [p for p in FORBIDDEN_PHRASES if re.sub(r"\s+", " ", p) in norm]
    if hits:
        sys.exit(f"BUILD FAILED — gated phrases present: {hits}")
    return out


def derive_build_md(md):
    lines = md.splitlines()
    # skip the banner when locating the title
    body = [ln for ln in lines if not ln.startswith("<!-- GENERATED")]
    title = body[0].lstrip("# ").strip()
    rest = body[1:]
    out = []
    for ln in rest:
        m = re.match(r"^(#{2,6})(\s+.*)$", ln)
        out.append(m.group(1)[1:] + m.group(2) if m else ln)
    yaml = ("---\n"
            f'title: "{title}"\n'
            "date: 2026-07-10\n"
            "geometry: margin=1in\n"
            "fontsize: 11pt\n"
            "colorlinks: true\n"
            "---\n\n")
    return yaml + "\n".join(out).strip() + "\n"


def main():
    check_only = "--check" in sys.argv
    md = render()
    if check_only:
        print("render OK (check mode, nothing written)")
        return
    open(os.path.join(HERE, "paper-v3.md"), "w", encoding="utf-8").write(BANNER + md)
    open(os.path.join(HERE, "paper-v3-build.md"), "w", encoding="utf-8").write(derive_build_md(md))
    for cmd in (
        ["pandoc", "paper-v3-build.md", "-s", "-o", "paper-v3.tex"],
        ["pandoc", "paper-v3-build.md", "-s", "--pdf-engine=xelatex",
         "-V", "mainfont=DejaVu Serif", "-V", "monofont=DejaVu Sans Mono",
         "-V", "sansfont=DejaVu Sans", "-V", "CJKmainfont=Noto Serif CJK SC",
         "-o", "paper-v3.pdf"],
    ):
        r = subprocess.run(cmd, cwd=HERE, capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit(f"BUILD FAILED — {cmd[0]} {cmd[-1]}: {r.stderr[:400]}")
        if "Missing character" in r.stderr:
            sys.exit(f"BUILD FAILED — missing glyphs in {cmd[-1]}")
    r = subprocess.run([sys.executable, os.path.join(ROOT, "repro", "verify_claims.py")],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("BUILD FAILED — independent checker rejected the build:\n"
                 + r.stdout[-1200:])
    print("BUILD OK — md/build.md/tex/pdf regenerated; independent checker green")


if __name__ == "__main__":
    main()
